html/themes/custom/common_design_subtheme/package-lock.json
html/themes/custom/common_design_subtheme/package.json

npm audit fix and socket.io update

CD-213 Dependency updates

---

composer.json
composer.lock
symfony.lock

https://humanitarian.atlassian.net/browse/SLT-44
Security update to ctools module

[SLT-44] update ctools to 3.6.0

---

composer.json
composer.lock
config/common_design_subtheme.settings.yml
symfony.lock

https://humanitarian.atlassian.net/browse/SLT-44

[SLT-44] Ctools security update

---

composer.json
composer.lock

https://humanitarian.atlassian.net/browse/OPS-7544

[OPS-7544] ctools update

---

composer.lock
symfony.lock

https://humanitarian.atlassian.net/browse/OPS-7688

[OPS-7688] update core to 8.9.18

---

composer.lock
symfony.lock

https://humanitarian.atlassian.net/browse/OPS-7997
Small updates to config_split, drush, drupal console devel, and stage_file_proxy

[OPS-7997] update dev modules

---

composer.json
composer.lock
config/core.extension.yml
config/user_expire.settings.yml
symfony.lock

https://humanitarian.atlassian.net/browse/OPS-7459
Add and enable user_expire module, with default setting of 180 days.

[OPS-7459] user_expire

---

composer.json
composer.lock

https://humanitarian.atlassian.net/browse/OPS-7998
Module updates for editor_advanced_link, entity_usage, imageapi_optimize, redirect, social_auth_hid, and token.

[OPS-7998] update contrib modules

---

.travis.yml
composer.json
composer.lock
html/modules/custom/linked_responsive_image_media_formatter/src/Plugin/Field/FieldFormatter/LinkedResponsiveImageMediaFormatter.php
html/modules/custom/slt_contacts/src/Form/SltContactsImportContactsForm.php
html/modules/custom/telephone_type/src/Plugin/Field/FieldWidget/TelephoneTypeDefaultWidget.php
symfony.lock

[OPS-7997] update coder module

---

composer.json
composer.lock
config/social_auth_hid.settings.yml

https://humanitarian.atlassian.net/browse/OPS-8135

[OPS-8135] bump social_auth_hid and small updates for other modules

---

composer.patches.json
config/user_expire.settings.yml

https://humanitarian.atlassian.net/browse/OPS-7459
Configures user_expire with the patches mentioned in https://github.com/UN-OCHA/assessmentregistry8-site/pull/360
The module was added in https://github.com/UN-OCHA/slt8-site/pull/53/files

[OPS-7459] user expire

---

composer.json
composer.lock
composer.patches.json
config/core.extension.yml
config/seckit.settings.yml
symfony.lock

chore: seckit improvements

---

config/pathauto.pattern.contact.yml
config/pathauto.pattern.pages.yml

fix: update pathauto config

---

config/csp.settings.yml

fix: repeat script-src rules for script-src-elem

---

config/csp.settings.yml

fix: correct typo

---

.github/workflows/composer-update.yml
composer.lock
config/csp.settings.yml

[OPS-8623] core security update 

---

composer.lock

Deploy 16-11-2022

---

composer.lock
composer.patches.json

chore: update manually as automatic update failed

---

.dockerignore
docker/Dockerfile

chore: update dockerignore and dockerfile

---

composer.json
composer.lock
config/config_split.config_split.config_dev.yml
config/core.extension.yml
config/environment_indicator.settings.yml
config/environment_indicator.switcher.dev.yml
config/environment_indicator.switcher.local.yml
config/environment_indicator.switcher.prod.yml
config_dev/environment_indicator.indicator.yml

chore: add and configure environment indicator

---

composer.patches.json

chore: update core patch

---

composer.json
composer.lock

chore: remove preserve-paths package

---

.github/workflows/composer-update.yml
.github/workflows/run-tests.yml

chore: allow running tests locally

---

html/themes/custom/common_design_subtheme/package-lock.json
html/themes/custom/common_design_subtheme/package.json

chore: run npm audit fix for subtheme packages

---

config/config_split.config_split.config_dev.yml
config/environment_indicator.switcher.dev.yml
config_dev/environment_indicator.switcher.local.yml

chore: adjust env indicator config

---

.gitignore
local/.env.example
local/README.md
local/docker-compose.yml
local/exec.sh
local/install.sh
local/shared/settings/services.yml
local/shared/settings/settings.local.php

chore: add local setup

---

composer.json
composer.lock
config/core.extension.yml
config/monitoring.sensor_config.ocha_common_design.yml
config/monitoring.sensor_config.ocha_current_composer_version.yml
config/monitoring.sensor_config.ocha_current_drupal_version.yml
config/monitoring.sensor_config.ocha_current_php_version.yml
config/monitoring.sensor_config.ocha_current_release.yml
config/monitoring.sensor_config.ocha_deployment_identifier.yml
config/monitoring.sensor_config.ocha_env_link_fixer.yml
config/monitoring.sensor_config.ocha_google_tag.yml
config/monitoring.sensor_config.ocha_gtm_barebones.yml
config/monitoring.sensor_config.ocha_ocha_monitoring.yml
config/monitoring.sensor_config.ocha_un_date.yml
config/monitoring.settings.yml
config/views.view.monitoring_sensor_results.yml

Refs: OPS-10130
See https://github.com/UN-OCHA/gms-site/pull/414 and https://github.com/UN-OCHA/ocha_monitoring/pull/2

chore: add ocha_monitoring module and config

---

.github/workflows/composer-update.yml
.github/workflows/run-tests.yml
composer.json
composer.lock

Refs: updates
Notably adds stage_file_proxy as https://jenkins.aws.ahconu.org/view/SLT/job/slt-testdeploy/ fails because it's expected:
```
+ docker exec -u appuser slt_stage_drupal_1 drush --root=/srv/www/html --uri=https://stage.savinglivestogether-unocha-org.ahconu.org/ en -y stage_file_proxy
In PmCommands.php line 329:
Unable to install modules stage_file_proxy due to missing modules stage_fil  
e_proxy.
```

tests: adjust for consistency

---

.github/workflows/composer-update-config.yml
.github/workflows/composer-update.yml
tests/docker-compose.yml

chore: config in updates

---

composer.lock
local/docker-compose.yml

chore: revert core version to 10.2.7 until 10.3 is better tested

---

composer.lock

chore: revert core versions for other packages too

---

composer.lock

chore: update phpspreadsheet

---

composer.json
composer.lock

chore: remove csp module and update phpoffice package

---

config/core.extension.yml

chore: remove unused allowed_formats modules

---

composer.json
composer.lock
docker/Dockerfile

updates: bump php version and update phpoffice

---

config/seckit.settings.yml

chore: csp exception for dragula library
